### ISSUE TITLE
UnicodeDecodeError in setup.py with python3

### ISSUE THREAD

**Issue by mrueg** [Tivix/django-common#31]
`` 

Running setup.py (path:/venv/build/django-common-helpers/setup.py) egg_info for package django-common-helpers
                     Traceback (most recent call last):
                        File "<string>", line 17, in <module>
                        File "/venv/build/django-common-helpers/setup.py", line 16, in <module>
                          long_description = f.read().strip()
                        File "/venv/lib/python3.4/encodings/ascii.py", line 26, in decode
                          return codecs.ascii_decode(input, self.errors)[0]
                      UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5737: ordinal not in range(128)
                      Complete output from command python setup.py egg_info:
                      Traceback (most recent call last):
                    File "<string>", line 17, in <module>
                    File "/venv/build/django-common-helpers/setup.py", line 16, in <module>

                      long_description = f.read().strip()

                    File "/venv/lib/python3.4/encodings/ascii.py", line 26, in decode

                      return codecs.ascii_decode(input, self.errors)[0]

                  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5737: ordinal not in range(128)
``

**Comment by sanjiely** [comment]
yes, I hit the same issue.
On windows 7, python 3.4.2, Django 1.9.2
Logs:
(env_workload) d:\projects\workload>pip install django-cron
Downloading/unpacking django-cron
  Downloading django-cron-0.4.6.tar.gz
  Running setup.py (path:D:\workspace\env_workload\build\django-cron\setup.py) egg_info for package django-cron

Requirement already satisfied (use --upgrade to upgrade): Django>=1.7.0 in d:\workspace\env_workload\lib\site-packages (from django-cron)
Downloading/unpacking django-common-helpers>=0.6.4 (from django-cron)
  Downloading django-common-helpers-0.8.0.tar.gz
  Running setup.py (path:D:\workspace\env_workload\build\django-common-helpers\setup.py) egg_info for package django-common-helpers
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "D:\workspace\env_workload\build\django-common-helpers\setup.py", line 16, in <module>
        long_description = f.read().strip()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 5739: illegal multibyte sequence
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "D:\workspace\env_workload\build\django-common-helpers\setup.py", line 16, in <module>

    long_description = f.read().strip()

UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 5739: illegal multibyte sequence

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in D:\workspace\env_workload\build\django-common-helpers
Storing debug log for failure in C:\Users\liy\pip\pip.log

**Comment by mrueg** [comment]
@chachra friendly ping? :)

**Comment by davidthewatson** [comment]
I've hit this installing on ubuntu 14.04 Dockerfile:

    remote: INFO -- :   Downloading django-common-helpers-0.8.0.tar.gz
    remote: INFO -- :   Running setup.py (path:/tmp/pip_build_root/django-common-helpers/setup.py) egg_info for package django-common-helpers
    remote: INFO -- :     Traceback (most recent call last):
    remote: INFO -- :       File "<string>", line 17, in <module>
    remote: INFO -- :       File "/tmp/pip_build_root/django-common-helpers/setup.py", line 16, in <module>
    remote: INFO -- :         long_description = f.read().strip()
    remote: INFO -- :       File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    remote: INFO -- :         return codecs.ascii_decode(input, self.errors)[0]
    remote: INFO -- :     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5737: ordinal not in range(128)
    remote: INFO -- :     Complete output from command python setup.py egg_info:
    remote: INFO -- :     Traceback (most recent call last):
    remote: 
    remote:   File "<string>", line 17, in <module>
    remote: 
    remote:   File "/tmp/pip_build_root/django-common-helpers/setup.py", line 16, in <module>
    remote: 
    remote:     long_description = f.read().strip()
    remote: 
    remote:   File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    remote: 
    remote:     return codecs.ascii_decode(input, self.errors)[0]
    remote: 
    remote: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5737: ordinal not in range(128)

**Comment by sanjiely** [comment]
Actually there is an "illegal" character in the file "README.rst", and it would be normal once I empty the file "README.rst".

This illegal character is '"0xa843" both in line 202 and line 203. It looks like a line, but not an ascii line.
The content of line 202 as below:
1. ``--length`` **–** is the length of the key ``default=50``

**Comment by vaskoMAYA** [comment]
@sanjiely is correct. These endashes on lines 202 and 203 of README.rst should be replaced with hyphens.

I copied the repo, changed the endashes to hyphens, and this error disappeared.

Since I could not make a pull request on this public repo, please update django-common's README.rst to have all endashes replaced with hyphens.

**Comment by CHRISTOPHERDIEHL** [comment]
Also currently having the issue when running in dockerfile

**Comment by maxim-kht** [comment]
Resolved in https://github.com/Tivix/django-common/pull/33
