### ISSUE TITLE
Issue in "compat.py" regarding Django version

### ISSUE THREAD

**Issue by Lambda511** [Tivix/django-common#40]
Hello,

There seems to be an issue in the _compat.py_ script, which makes it not work properly with Django 2.0 and above. 

```python
if VERSION[1] >= 8:
    from django.contrib.admin.utils import unquote, flatten_fieldsets
else:
    from django.contrib.admin.util import unquote, flatten_fieldsets
```
It should use "**from django.contrib.admin.utils**" for Django 2.0+ also, not to fall back on the else branch (where it should go only for versions before 1.8). 

A quick fix could be rewrite the IF block as following:

```python
if VERSION[0] < 1 or (VERSION[0] == 1 and VERSION[1] < 8):
    from django.contrib.admin.util import unquote, flatten_fieldsets
else:
    from django.contrib.admin.utils import unquote, flatten_fieldsets
```

I am not sure if this will have any other unexpected results in other parts of the library because I haven't studied all the code. But maybe this helps to fix the issue that arises with Django 2.0+.

Thanks,

**Comment by chachra** [comment]
resolved
